version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: factecho-node-server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    volumes:
      - ./shared:/app/shared  # Mount the shared directory
    restart: always

  # client:
  #   build:
  #     context: .
  #     dockerfile: ./client/react/Dockerfile
  #   container_name: factecho-react-client
  #   ports:
  #     - "5173:5173"
  #   env_file:
  #     - ./client/react/.env.local
  #   volumes:
  #     - ./shared:/app/shared  # Mount the shared directory
  #   depends_on:
  #     - server
  #   restart: always